import type { Tool, User } from "./interfaces";


export const CURRENT_USER: User = {
  id: 1,
  name: "Mr. Joseph Tremblay",
  email: "brandi.stiedemann@gmail.com",
  department_id: 1,
  role: "Head of Engineering",
  active: false,
  joined_at: "2023-04-25"
};

export const RECENT_TOOLS: Tool[] = [
  {
    id: 1,
    name: "Slack",
    description: "Team messaging and collaboration platform",
    vendor: "Slack Technologies",
    category: "Communication",
    monthly_cost: 2225,
    previous_month_cost: 2099,
    owner_department: "Communication",
    status: "expiring",
    website_url: "https://slack.com",
    active_users_count: 205,
    icon_url: "https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png",
    created_at: "2024-06-08T20:24:54.164Z",
    updated_at: "2025-09-30T18:00:41.676Z"
  },
  {
    id: 2,
    name: "Figma",
    description: "Collaborative design and prototyping tool.",
    vendor: "Figma Inc",
    category: "Design",
    monthly_cost: 450, // Ajouté car manquant dans ton JSON partiel pour éviter les bugs de tri
    previous_month_cost: 400,
    owner_department: "Design",
    status: "unused",
    website_url: "https://figma.com",
    active_users_count: 15,
    icon_url: "https://static.figma.com/app/icon/1/favicon.png",
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2025-01-01T00:00:00.000Z"
  },
  {
    id: 3,
    name: "GitHub",
    description: "Version control and code collaboration platform.",
    vendor: "Microsoft",
    category: "Development",
    monthly_cost: 890, // Ajouté car manquant
    previous_month_cost: 800,
    owner_department: "Operations",
    status: "unused",
    website_url: "https://github.com",
    active_users_count: 45,
    icon_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2025-01-01T00:00:00.000Z"
  },
  {
    id: 4,
    name: "Notion",
    description: "All-in-one workspace for notes, docs, and project management",
    vendor: "Notion Labs",
    category: "Productivity",
    monthly_cost: 673,
    previous_month_cost: 741,
    owner_department: "Communication",
    status: "active",
    website_url: "https://notion.com",
    active_users_count: 149,
    icon_url: "https://www.notion.so/images/favicon.ico",
    created_at: "2025-02-13T00:50:21.292Z",
    updated_at: "2025-09-11T20:12:10.730Z"
  },
  {
    id: 5,
    name: "Adobe Creative Cloud",
    description: "Creative suite for design and video editing",
    vendor: "Adobe",
    category: "Design",
    monthly_cost: 623,
    previous_month_cost: 623,
    owner_department: "Operations",
    status: "active",
    website_url: "https://adobecreativecloud.com",
    active_users_count: 14,
    icon_url: "https://www.adobe.com/content/dam/cc/icons/creative-cloud.svg",
    created_at: "2024-03-30T23:14:16.184Z",
    updated_at: "2025-08-10T15:19:40.685Z"
  },
  {
    id: 6,
    name: "Jira",
    description: "Project management and issue tracking for agile teams",
    vendor: "Atlassian",
    category: "Project Management",
    monthly_cost: 611,
    previous_month_cost: 607,
    owner_department: "Communication",
    status: "active",
    website_url: "https://jira.com",
    active_users_count: 52,
    icon_url: "https://wac-cdn.atlassian.com/dam/jcr:e348b562-4152-4cdc-8a55-3d297e509cc8/Jira%20Software-blue.svg",
    created_at: "2025-01-20T14:35:44.624Z",
    updated_at: "2025-11-25T19:20:26.956Z"
  },
  {
    id: 7,
    name: "Zoom",
    description: "Video conferencing and online meeting platform",
    vendor: "Zoom Video",
    category: "Communication",
    monthly_cost: 405,
    previous_month_cost: 403,
    owner_department: "Engineering",
    status: "unused",
    website_url: "https://zoom.com",
    active_users_count: 63,
    icon_url: "https://d24cgw3uvb9a9h.cloudfront.net/static/93516/image/new/ZoomLogo_112x112.png",
    created_at: "2024-07-02T05:28:48.824Z",
    updated_at: "2025-11-26T07:16:45.776Z"
  },
  {
    id: 8,
    name: "Office 365",
    description: "Productivity suite with Office apps and cloud services",
    vendor: "Microsoft",
    category: "Productivity",
    monthly_cost: 1198,
    previous_month_cost: 1194,
    owner_department: "Operations",
    status: "active",
    website_url: "https://office365.com",
    active_users_count: 55,
    icon_url: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4OsXp",
    created_at: "2025-05-01T22:49:05.615Z",
    updated_at: "2025-07-30T22:06:52.311Z"
  },
  {
    id: 9,
    name: "Canva",
    description: "Online design and visual content creation platform",
    vendor: "Canva",
    category: "Design",
    monthly_cost: 170,
    previous_month_cost: 151,
    owner_department: "Engineering",
    status: "active",
    website_url: "https://canva.com",
    active_users_count: 21,
    icon_url: "https://static.canva.com/web/images/8439b51bb7a19f6e65ce1064bc37c197.png",
    created_at: "2024-06-25T03:29:05.983Z",
    updated_at: "2024-12-19T23:42:54.208Z"
  },
  {
    id: 10,
    name: "HubSpot",
    description: "CRM and marketing automation platform",
    vendor: "HubSpot",
    category: "Sales & Marketing",
    monthly_cost: 979,
    previous_month_cost: 932,
    owner_department: "Communication",
    status: "active",
    website_url: "https://hubspot.com",
    active_users_count: 23,
    icon_url: "https://www.hubspot.com/hubfs/assets/hubspot.com/style-guide/brand-guidelines/hubspot-logo-black.svg",
    created_at: "2024-01-18T19:41:51.001Z",
    updated_at: "2025-03-01T16:16:03.978Z"
  },
  {
    id: 11,
    name: "Williamson - Schamberger Project Management",
    description: "benchmark e-business interfaces solution",
    vendor: "Romaguera - Williamson",
    category: "Project Management",
    monthly_cost: 690,
    previous_month_cost: 698,
    owner_department: "Engineering",
    status: "active",
    website_url: "https://williamson-schambergerprojectmanagement.com",
    active_users_count: 28,
    icon_url: "https://logo.clearbit.com/johnston-bruen.com",
    created_at: "2025-02-25T04:56:18.882Z",
    updated_at: "2024-09-05T07:35:10.250Z"
  },
  {
    id: 12,
    name: "Walter - Runolfsson Analytics",
    description: "target frictionless supply-chains solution",
    vendor: "Prosacco, Mayer and Cummings",
    category: "Analytics",
    monthly_cost: 920,
    previous_month_cost: 848,
    owner_department: "Communication",
    status: "expiring",
    website_url: "https://walter-runolfssonanalytics.com",
    active_users_count: 31,
    icon_url: "https://logo.clearbit.com/skiles,rippinandbeier.com",
    created_at: "2024-10-03T02:04:18.118Z",
    updated_at: "2025-05-04T04:50:47.640Z"
  },
  {
    id: 13,
    name: "Ritchie, Schowalter and Yundt Development",
    description: "envisioneer killer web services solution",
    vendor: "Mohr LLC",
    category: "Development",
    monthly_cost: 549,
    previous_month_cost: 608,
    owner_department: "Marketing",
    status: "expiring",
    website_url: "https://ritchie,schowalterandyundtdevelopment.com",
    active_users_count: 35,
    icon_url: "https://logo.clearbit.com/cassinllc.com",
    created_at: "2024-12-23T18:07:59.004Z",
    updated_at: "2024-12-25T18:04:11.057Z"
  },
  {
    id: 14,
    name: "Nikolaus - Spinka Security",
    description: "orchestrate real-time paradigms solution",
    vendor: "Kunze, Nienow and Nader",
    category: "Security",
    monthly_cost: 1041,
    previous_month_cost: 951,
    owner_department: "Design",
    status: "active",
    website_url: "https://nikolaus-spinkasecurity.com",
    active_users_count: 28,
    icon_url: "https://logo.clearbit.com/sipesandsons.com",
    created_at: "2025-03-22T08:53:39.617Z",
    updated_at: "2025-06-02T01:03:25.156Z"
  },
  {
    id: 15,
    name: "Hilll LLC Security",
    description: "orchestrate B2B relationships solution",
    vendor: "test",
    category: "Security",
    monthly_cost: 1567, // J'ai converti le string "1567" en number
    previous_month_cost: 435,
    owner_department: "Engineering",
    status: "active",
    website_url: "https://hilllllcsecurity.com",
    active_users_count: 21,
    icon_url: "https://logo.clearbit.com/koelpingroup.com",
    created_at: "2025-12-04T14:53:10.508Z",
    updated_at: "2025-12-04T14:53:10.508Z"
  },
  {
    id: 16,
    name: "Hettinger Inc Development",
    description: "iterate granular eyeballs solution",
    vendor: "Lockman, Windler and O'Kon",
    category: "Development",
    monthly_cost: 977,
    previous_month_cost: 968,
    owner_department: "Operations",
    status: "unused",
    website_url: "https://hettingerincdevelopment.com",
    active_users_count: 31,
    icon_url: "https://logo.clearbit.com/rathandsons.com",
    created_at: "2024-06-30T21:10:31.641Z",
    updated_at: "2025-03-03T08:47:29.534Z"
  },
  {
    id: 17,
    name: "Kozey - Pagac Finance",
    description: "leverage transparent partnerships solution",
    vendor: "O'Connell, Kuvalis and Pfannerstill",
    category: "Finance",
    monthly_cost: 987,
    previous_month_cost: 965,
    owner_department: "Marketing",
    status: "expiring",
    website_url: "https://kozey-pagacfinance.com",
    active_users_count: 45,
    icon_url: "https://logo.clearbit.com/lindgren-beier.com",
    created_at: "2025-01-18T21:18:37.020Z",
    updated_at: "2025-04-04T00:32:20.700Z"
  },
  {
    id: 18,
    name: "Mueller and Sons Security",
    description: "enhance killer niches solution",
    vendor: "Terry - Feest",
    category: "Security",
    monthly_cost: 373,
    previous_month_cost: 382,
    owner_department: "Marketing",
    status: "expiring",
    website_url: "https://muellerandsonssecurity.com",
    active_users_count: 29,
    icon_url: "https://logo.clearbit.com/rolfson-krajcik.com",
    created_at: "2024-09-25T23:49:06.252Z",
    updated_at: "2024-09-10T12:08:34.884Z"
  },
  {
    id: 19,
    name: "Johnston Inc Security",
    description: "engage open-source experiences solution",
    vendor: "Pouros - Turcotte",
    category: "Security",
    monthly_cost: 713,
    previous_month_cost: 685,
    owner_department: "Design",
    status: "active",
    website_url: "https://johnstonincsecurity.com",
    active_users_count: 29,
    icon_url: "https://logo.clearbit.com/parisian-reinger.com",
    created_at: "2024-09-06T21:29:03.878Z",
    updated_at: "2025-03-27T13:19:16.415Z"
  },
  {
    id: 20,
    name: "Jacobi, Rosenbaum and Kiehn Development",
    description: "cultivate world-class metrics solution",
    vendor: "Vandervort, Kihn and Rutherford",
    category: "Development",
    monthly_cost: 718,
    previous_month_cost: 692,
    owner_department: "Communication",
    status: "active",
    website_url: "https://jacobi,rosenbaumandkiehndevelopment.com",
    active_users_count: 29,
    icon_url: "https://logo.clearbit.com/connelly,heidenreichandwaters.com",
    created_at: "2024-08-26T02:41:13.582Z",
    updated_at: "2025-01-27T08:43:34.151Z"
  },
  {
    id: 21,
    name: "Berge Group HR",
    description: "utilize viral paradigms solution",
    vendor: "Mante, Schultz and Bradtke",
    category: "HR",
    monthly_cost: 134,
    previous_month_cost: 139,
    owner_department: "Operations",
    status: "active",
    website_url: "https://bergegrouphr.com",
    active_users_count: 21,
    icon_url: "https://logo.clearbit.com/toy-kreiger.com",
    created_at: "2025-02-15T12:14:08.784Z",
    updated_at: "2024-12-01T12:47:50.454Z"
  },
  {
    id: 22,
    name: "Schowalter, Harris and Crooks Security",
    description: "generate world-class e-markets solution",
    vendor: "Upton Group",
    category: "Security",
    monthly_cost: 762,
    previous_month_cost: 742,
    owner_department: "Communication",
    status: "active",
    website_url: "https://schowalter,harrisandcrookssecurity.com",
    active_users_count: 38,
    icon_url: "https://logo.clearbit.com/handandsons.com",
    created_at: "2024-12-25T11:01:15.178Z",
    updated_at: "2024-10-02T13:03:57.228Z"
  },
];